package com.ayt.webui.webuimapper.mapper;

import com.ayt.webui.webuimapper.entity.ProjectCase;
import com.ayt.webui.webuimapper.entity.ProjectCaseExample;
import java.util.List;

public interface ProjectCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case
     *
     * @mbg.generated
     */
    int insert(ProjectCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case
     *
     * @mbg.generated
     */
    int insertSelective(ProjectCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case
     *
     * @mbg.generated
     */
    List<ProjectCase> selectByExample(ProjectCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case
     *
     * @mbg.generated
     */
    ProjectCase selectByPrimaryKey(Integer caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectCase record);
}