package com.ayt.webui.webuimapper.mapper;

import com.ayt.webui.webuimapper.entity.ProjectCaseSteps;
import com.ayt.webui.webuimapper.entity.ProjectCaseStepsExample;
import java.util.List;

public interface ProjectCaseStepsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case_steps
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer stepId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case_steps
     *
     * @mbg.generated
     */
    int insert(ProjectCaseSteps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case_steps
     *
     * @mbg.generated
     */
    int insertSelective(ProjectCaseSteps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case_steps
     *
     * @mbg.generated
     */
    List<ProjectCaseSteps> selectByExample(ProjectCaseStepsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case_steps
     *
     * @mbg.generated
     */
    ProjectCaseSteps selectByPrimaryKey(Integer stepId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case_steps
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectCaseSteps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_case_steps
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectCaseSteps record);
}