package com.ayt.webui.webuimapper.entity;

import java.util.Date;

public class ProjectCase {
    /**
     * 测试用例ID case_id
     */
    private Integer caseId;

    /**
     * 用例编号排序 case_serial_number
     */
    private Integer caseSerialNumber;

    /**
     * 用例标识 case_sign
     */
    private String caseSign;

    /**
     * 用例名称 case_name
     */
    private String caseName;

    /**
     * 关联项目ID project_id
     */
    private Integer projectId;

    /**
     * 关联项目模块ID module_id
     */
    private Integer moduleId;

    /**
     * 默认类型 0 HTTP接口 1 Web UI 2 API驱动  3移动端 case_type
     */
    private Integer caseType;

    /**
     * 前置步骤失败，后续步骤是否继续，0：中断，1：继续 failcontinue
     */
    private Integer failcontinue;

    /**
     * 创建者 create_by
     */
    private String createBy;

    /**
     * 创建时间 create_time
     */
    private Date createTime;

    /**
     * 更新者 update_by
     */
    private String updateBy;

    /**
     * 更新时间 update_time
     */
    private Date updateTime;

    /**
     * 备注 remark
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.case_id
     *
     * @return the value of project_case.case_id
     *
     * @mbg.generated
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.case_id
     *
     * @param caseId the value for project_case.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.case_serial_number
     *
     * @return the value of project_case.case_serial_number
     *
     * @mbg.generated
     */
    public Integer getCaseSerialNumber() {
        return caseSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.case_serial_number
     *
     * @param caseSerialNumber the value for project_case.case_serial_number
     *
     * @mbg.generated
     */
    public void setCaseSerialNumber(Integer caseSerialNumber) {
        this.caseSerialNumber = caseSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.case_sign
     *
     * @return the value of project_case.case_sign
     *
     * @mbg.generated
     */
    public String getCaseSign() {
        return caseSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.case_sign
     *
     * @param caseSign the value for project_case.case_sign
     *
     * @mbg.generated
     */
    public void setCaseSign(String caseSign) {
        this.caseSign = caseSign == null ? null : caseSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.case_name
     *
     * @return the value of project_case.case_name
     *
     * @mbg.generated
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.case_name
     *
     * @param caseName the value for project_case.case_name
     *
     * @mbg.generated
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.project_id
     *
     * @return the value of project_case.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.project_id
     *
     * @param projectId the value for project_case.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.module_id
     *
     * @return the value of project_case.module_id
     *
     * @mbg.generated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.module_id
     *
     * @param moduleId the value for project_case.module_id
     *
     * @mbg.generated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.case_type
     *
     * @return the value of project_case.case_type
     *
     * @mbg.generated
     */
    public Integer getCaseType() {
        return caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.case_type
     *
     * @param caseType the value for project_case.case_type
     *
     * @mbg.generated
     */
    public void setCaseType(Integer caseType) {
        this.caseType = caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.failcontinue
     *
     * @return the value of project_case.failcontinue
     *
     * @mbg.generated
     */
    public Integer getFailcontinue() {
        return failcontinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.failcontinue
     *
     * @param failcontinue the value for project_case.failcontinue
     *
     * @mbg.generated
     */
    public void setFailcontinue(Integer failcontinue) {
        this.failcontinue = failcontinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.create_by
     *
     * @return the value of project_case.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.create_by
     *
     * @param createBy the value for project_case.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.create_time
     *
     * @return the value of project_case.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.create_time
     *
     * @param createTime the value for project_case.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.update_by
     *
     * @return the value of project_case.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.update_by
     *
     * @param updateBy the value for project_case.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.update_time
     *
     * @return the value of project_case.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.update_time
     *
     * @param updateTime the value for project_case.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case.remark
     *
     * @return the value of project_case.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case.remark
     *
     * @param remark the value for project_case.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}