package com.ayt.webui.webuimapper.entity;

import java.util.Date;

public class ProjectCaseParams {
    /**
     * 用例参数ID params_id
     */
    private Integer paramsId;

    /**
     * 参数名称 params_name
     */
    private String paramsName;

    /**
     * 参数值 params_value
     */
    private String paramsValue;

    /**
     * 项目ID project_id
     */
    private Integer projectId;

    /**
     * 创建者 create_by
     */
    private String createBy;

    /**
     * 创建时间 create_time
     */
    private Date createTime;

    /**
     * 更新者 update_by
     */
    private String updateBy;

    /**
     * 更新时间 update_time
     */
    private Date updateTime;

    /**
     * 备注 remark
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.params_id
     *
     * @return the value of project_case_params.params_id
     *
     * @mbg.generated
     */
    public Integer getParamsId() {
        return paramsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.params_id
     *
     * @param paramsId the value for project_case_params.params_id
     *
     * @mbg.generated
     */
    public void setParamsId(Integer paramsId) {
        this.paramsId = paramsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.params_name
     *
     * @return the value of project_case_params.params_name
     *
     * @mbg.generated
     */
    public String getParamsName() {
        return paramsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.params_name
     *
     * @param paramsName the value for project_case_params.params_name
     *
     * @mbg.generated
     */
    public void setParamsName(String paramsName) {
        this.paramsName = paramsName == null ? null : paramsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.params_value
     *
     * @return the value of project_case_params.params_value
     *
     * @mbg.generated
     */
    public String getParamsValue() {
        return paramsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.params_value
     *
     * @param paramsValue the value for project_case_params.params_value
     *
     * @mbg.generated
     */
    public void setParamsValue(String paramsValue) {
        this.paramsValue = paramsValue == null ? null : paramsValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.project_id
     *
     * @return the value of project_case_params.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.project_id
     *
     * @param projectId the value for project_case_params.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.create_by
     *
     * @return the value of project_case_params.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.create_by
     *
     * @param createBy the value for project_case_params.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.create_time
     *
     * @return the value of project_case_params.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.create_time
     *
     * @param createTime the value for project_case_params.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.update_by
     *
     * @return the value of project_case_params.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.update_by
     *
     * @param updateBy the value for project_case_params.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.update_time
     *
     * @return the value of project_case_params.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.update_time
     *
     * @param updateTime the value for project_case_params.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_case_params.remark
     *
     * @return the value of project_case_params.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_case_params.remark
     *
     * @param remark the value for project_case_params.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}